### ISSUE TITLE
kikndly add these to the template

### ISSUE THREAD

**Issue by umashankar-rapiqube** [risabh-rapidqube/nodejs-template#1]
1. create a additional folders called
 - Model
 - Adapter
	- External Systems
 -DB
	-Mongo
	-Mysql
	-Oracle
 -BlockchainSDK
	-MultichainSDK
	-FabricSDK
 -validations
 -Utils
	-emailUtil
	-SMSNotificationUtil
 -core

**Comment by risabh-rapidqube** [comment]
added adapters folder to the project directory and changed functions folder name to core engine.
